FROM debian:trixie-slim

RUN apt update && \
    apt install -y \
		build-essential \
		dub \
		git \
		libvted-3-dev

ARG TILIX_COMMIT_SHA=46b6a7c6b318257bba145d527cbf4a09fa9fbb43

RUN git clone https://github.com/gnunn1/tilix.git && \
	cd tilix && \
	git checkout $TILIX_COMMIT_SHA && \
	dub build
