FROM fedora:43

RUN dnf install -y \
		dub \
		git \
		ldc \
		vte-devel

RUN git clone https://github.com/gnunn1/tilix.git && \
	cd tilix && \
	# Use static libraries (https://github.com/gnunn1/tilix/issues/2183)
	sed -i 's/-link-defaultlib-shared=false/-link-defaultlib-shared=true/' dub.json && \
	dub build
